[package]
name = "odroidssh"
version = "0.1.0"
authors = ["Tomasz Cichocki <cichymail@gmail.com>"]

[dependencies]
thrussh = "0.21.2"
thrussh-keys = "0.11.9"
futures = "0.1.27"
tokio = "0.1.19"
env_logger = "0.5.13"
log = "0.4"
yaml-rust = "0.4.3"
enum-map = "0.5.0"
opener = "0.4.0"